# Generated by Django 5.1.4 on 2025-01-22 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('channel', models.CharField(max_length=100, unique=True, verbose_name='频道名称')),
            ],
            options={
                'verbose_name': '频道',
                'verbose_name_plural': '频道',
            },
        ),
        migrations.CreateModel(
            name='customer_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100, unique=True, verbose_name='MAC地址')),
                ('app', models.JSONField(verbose_name='应用')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.channel', verbose_name='频道')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
