# Generated by Django 5.1.4 on 2025-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requestion_of_ali',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('mac', models.CharField(max_length=100, unique=True, verbose_name='MAC地址')),
                ('app', models.JSONField(verbose_name='应用')),
            ],
            options={
                'verbose_name': 'ali服务器信息',
                'verbose_name_plural': 'ali服务器信息',
            },
        ),
    ]
