# Generated by Django 5.1.4 on 2025-01-22 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apk_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='名称')),
                ('packagename', models.CharField(max_length=100, unique=True, verbose_name='包名')),
                ('version', models.FloatField(blank=True, null=True, verbose_name='版本号')),
            ],
            options={
                'verbose_name': 'APK信息',
                'verbose_name_plural': 'APK信息',
                'indexes': [models.Index(fields=['name'], name='name_idx')],
            },
        ),
        migrations.CreateModel(
            name='requestion_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appp.apk_information', verbose_name='APK信息')),
            ],
            options={
                'verbose_name': '请求信息',
                'verbose_name_plural': '请求信息',
            },
        ),
    ]
