# Generated by Django 5.1.4 on 2025-01-18 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apk_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('version', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='appp_apk_in_name_cc3265_idx')],
            },
        ),
        migrations.CreateModel(
            name='requestion_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appp.apk_information')),
            ],
        ),
    ]
